version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
  - package_manager: "javascript"
    directory: "/examples/using-gatsby-source-local-git"
    update_schedule: "weekly"
